baseURL: "https://keqizeng.github.io/"
languageCode: en-us
title: Ketch's Blog
theme: PaperMod

minify:
  disableXML: true
  minifyOutput: true

markup:
  highlight:
    lineNos: false
    lineNumbersInTable: false
    noClasses: false
    tabWidth: 4

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      tag: tags
      series: series
    params:
      homeInfoParams:
        Title: Hi there ğŸ‘‹
        Content: Welcome to my blog! My name is Keqi Zeng, you can also call me Ketch. I'm a master student of TU Darmstadt ğŸ‡©ğŸ‡ª, major in Robotics.

    menu:
      main:
        - name: ğŸ“š Archive
          url: archives/
          weight: 1
        - name: ğŸ·ï¸ Tags
          url: tags/
          weight: 2
        - name: ğŸ“ About
          url: about/
          weight: 3
        - name: ğŸ”
          url: search/
          weight: 4

params:
  defaultTheme: auto # to switch between dark or light according to browser theme
  author: Ketch
  DateFormat: "2006-01-02"
  socialIcons:
    - name: github
      url: https://github.com/KeqiZeng
    - name: email
      url: mailto:ketchz0206@outlook.com

  math: true
  enableEmoji: true
  enableGitInfo: true
  ShowWordCount: true
  ShowReadingTime: true
  ShowToc: true
  TocOpen: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
